version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 875207630257.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t my-django-app .

  post_build:
  commands:
    - echo Tagging the Docker image...
    - docker tag my-django-app:latest 875207630257.dkr.ecr.us-east-1.amazonaws.com/my-django-app:latest
    - echo Pushing the Docker image to Amazon ECR...
    - docker push 875207630257.dkr.ecr.us-east-1.amazonaws.com/my-django-app:latest

