version: "3.8"

services:
  django:
    build:
      context: ./bookStoreApi
    container_name: django-app
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 600 bookStoreApi.wsgi:application
    volumes:
      - ./django:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Use .env file for environment variables

  nextjs:
    build:
      context: ./nextjs
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env  # Use .env file for environment variables

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  mysql-data:
