version: "3.8"

services:
  django:
    build:
      context: ./bookStoreApi
    container_name: django-app
    command: gunicorn --workers 3 --bind 0.0.0.0:8000 --timeout 600 bookStoreApi.wsgi:application
    volumes:
      - ./bookStoreApi:/usr/src/app
      - /var/log/docker/django-app:/var/log/django-app

    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Use .env file for environment variables

  nextjs:
    build:
      context: ./next-js
    container_name: nextjs-app
    volumes:
      - /var/log/docker/nextjs-app:/var/log/nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env  # Use .env file for environment variables
  redis:
    image: "redis:latest"
    container_name: bookstore-redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
    container_name: bookstore-celery-worker
    command: celery -A bookStoreApi worker -l INFO
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./bookStoreApi:/usr/src/app
      - /var/log/docker/django-app:/var/log/django-app
  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
      - /var/log/docker/mysql-db:/var/log/mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"

volumes:
  mysql-data:
