import type { Metadata } from "next";
import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Alert from "./components/main/Alert";
import Footer from "./components/main/Footer"
import { OrderProvider } from "./contexts/OrderContext";
import { ErrorProvider } from "./contexts/ErrorContext";
import dynamic from 'next/dynamic';

// Dynamically import WelcomeSection
const Navbar = dynamic(() => import('./components/navbar/Navbar'), { ssr: false });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
      <ErrorProvider><OrderProvider>
        <header><Navbar />
        <Alert />
        </header>
        <main>{children}</main>
        <footer><Footer/></footer>
        </OrderProvider></ErrorProvider>
      </body>
    </html>
  );
}
