# Generated by Django 4.2.9 on 2024-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_session_id_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="post_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
