# Generated by Django 4.2.9 on 2024-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Sold'), ('PENDING', 'Pending')], default='OPEN', max_length=50, verbose_name='Status of the order'),
        ),
    ]
