# Generated by Django 4.2.9 on 2024-06-06 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ant",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.CharField(
                default="No description", max_length=5000, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="loc",
            field=models.CharField(default="no-loc", max_length=255),
        ),
        migrations.AddField(
            model_name="book",
            name="page",
            field=models.IntegerField(
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="remain",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="supplier",
            field=models.CharField(default="unknown supplier", max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="condition_description",
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(
                choices=[
                    ("PAPERBACK", "Paperback"),
                    ("HARDCOVER", "Hardcover"),
                    ("POCKET", "Pocket"),
                ],
                default="Paperback",
                max_length=50,
                null=True,
                verbose_name="Cover type of the book",
            ),
        ),
        migrations.AlterField(
            model_name="book", name="title", field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="book",
            name="year",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1700),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
    ]
